services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boozer_test_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boozer
    ports:
      - 5001:5432
    # no volumes, data will not persist
