# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go backend build

on:
  push:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      # Build for Linux AMD64
      - name: Build for Linux AMD64
        run: |
          cd backend
          go get boozer
          GOOS=linux GOARCH=amd64 go build -o boozer_amd64
      - name: Upload Linux AMD64 binary
        uses: actions/upload-artifact@v4
        with:
          name: boozer_amd64
          path: backend/boozer_amd64
